name: supermarket_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  intl: ^0.17.0
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+5
  fluttertoast: ^8.2.2
  image_picker: ^0.8.6+4

  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  mobx: ^2.1.3
  
  firebase_storage: ^11.2.5
  firebase_core: ^2.15.0
  rxdart: ^0.27.7
  path_provider: ^2.0.15
  shared_preferences: ^2.0.15
  skeletons: ^0.0.3
  google_fonts: 4.0.3
  auto_size_text: 3.0.0
  badges: 2.0.2
  toggle_switch: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  lints: ^2.0.1
  mobx_codegen: ^2.1.1
  source_gen: ^1.2.6
  modular_test: ^2.0.0

  flutter_native_splash: ^2.2.17

flutter:
  uses-material-design: true
  assets:
    - assets/images/
